name: Update Football Schedule Daily
on:
  schedule:
    - cron: '0 10 * * *'  # 10 AM UTC = 5 AM Colombia
  workflow_dispatch:      # Ejecución manual

jobs:
  update-schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium
          
      - name: Run scraping script
        run: python scraper_diario.py
        
      - name: Update bot.py with new matches
        run: python actualizar_bot.py
        
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add bot.py
          git diff --quiet && git diff --staged --quiet || git commit -m "🤖 Auto-update: Nuevos partidos del día"
          git push
